/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roleplayinggame;

import java.util.Random;

/**
 *
 * @author 
 */
public class CharacterCreationScreen extends javax.swing.JFrame {

    /**
     * Creates new form CharacterCreationScreen
     */
    public CharacterCreationScreen() {
        initComponents();
        
    }
     
    public String Summary(){
            String name=jT_name.getText();
            String points=jT_points.getText();
            String defence=jT_defence.getText();
            String agility=jT_agility.getText();
            String attack=jT_base_attack.getText();
            String modifier=jT_attack_mod.getText();
            String weight=jT_weight.getText();
            
            //
            String sumaryName=name;
            String sumaryPoints=points;
            String sumaryDefence=defence;
            String sumaryAgility=agility;
            String sumaryAttack=attack;
            String sumaryModifier=modifier;
            String sumaryWeight=weight;
            
            return sumaryName;
           // return sumaryPoints;
            
     
        
    }
        
    
    
    public void GenegateRandom(){
        Random rand = new Random(); //instance of random class
      int upperbound = 101;
        //generate random values from 0-100
      int int_random = rand.nextInt(upperbound); 
      jT_points.setText(Integer.toString(rand.nextInt(int_random)));
      jT_defence.setText(Integer.toString(rand.nextInt(int_random)));
      jT_agility.setText(Integer.toString(rand.nextInt(int_random)));
      jT_base_attack.setText(Integer.toString(rand.nextInt(int_random)));
      
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jL_Character = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jT_points = new javax.swing.JTextField();
        jT_agility = new javax.swing.JTextField();
        jT_defence = new javax.swing.JTextField();
        jT_base_attack = new javax.swing.JTextField();
        jTf_CharacterDesc = new javax.swing.JTextField();
        jT_name = new javax.swing.JTextField();
        jB_warrior = new javax.swing.JRadioButton();
        jB_wizard = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jB_sword = new javax.swing.JRadioButton();
        jB_dagger = new javax.swing.JRadioButton();
        jB_hammer = new javax.swing.JRadioButton();
        jT_weight = new javax.swing.JTextField();
        jTf_WeaponDesc = new javax.swing.JTextField();
        jT_attack_mod = new javax.swing.JTextField();
        btn_start_battle = new javax.swing.JButton();
        jL_Weapon = new javax.swing.JLabel();
        jB_cleric = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(56, 149, 211));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel1.setText("Enter name");

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel2.setText("Character Generator");

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel3.setText("Character Type");

        jL_Character.setText("character");

        jLabel7.setText("Base Attack");

        jLabel8.setText("Agility");

        jLabel9.setText("Defence");

        jLabel10.setText("Hit Points");

        jLabel11.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel11.setText("Character Stats");

        jT_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_pointsActionPerformed(evt);
            }
        });

        jT_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nameActionPerformed(evt);
            }
        });

        buttonGroup1.add(jB_warrior);
        jB_warrior.setText("Warrier");
        jB_warrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_warriorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jB_wizard);
        jB_wizard.setText("Wizard");
        jB_wizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_wizardActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jButton1.setText("Reroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel12.setText("Select your weapon");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Attack Modifier");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Weight");

        jLabel16.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel16.setText("Weapon Stats");

        buttonGroup2.add(jB_sword);
        jB_sword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_sword.setText("Sword");
        jB_sword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_swordActionPerformed(evt);
            }
        });

        buttonGroup2.add(jB_dagger);
        jB_dagger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_dagger.setText("Dagger");
        jB_dagger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_daggerActionPerformed(evt);
            }
        });

        buttonGroup2.add(jB_hammer);
        jB_hammer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_hammer.setText("Hammer");
        jB_hammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_hammerActionPerformed(evt);
            }
        });

        btn_start_battle.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        btn_start_battle.setText("Start Battle");
        btn_start_battle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start_battleActionPerformed(evt);
            }
        });

        jL_Weapon.setText("a weapon");

        buttonGroup1.add(jB_cleric);
        jB_cleric.setText("Cleric");
        jB_cleric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_clericActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTf_CharacterDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTf_WeaponDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_sword)
                                    .addComponent(jB_dagger)
                                    .addComponent(jB_hammer))
                                .addGap(57, 57, 57)
                                .addComponent(jL_Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_warrior)
                            .addComponent(jB_wizard)
                            .addComponent(jB_cleric))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_Character, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jT_points, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT_base_attack, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT_agility, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT_defence, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(131, 131, 131))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel16))
                            .addContainerGap()))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jT_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(40, 40, 40)
                                    .addComponent(jT_attack_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btn_start_battle)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_points, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jT_defence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_agility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jT_base_attack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Character, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_wizard)
                                .addGap(42, 42, 42)
                                .addComponent(jB_warrior)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_cleric)
                        .addGap(35, 35, 35)
                        .addComponent(jTf_CharacterDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_dagger)
                                .addGap(18, 18, 18)
                                .addComponent(jB_sword)
                                .addGap(26, 26, 26)
                                .addComponent(jB_hammer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jL_Weapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTf_WeaponDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jT_attack_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jT_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_start_battle)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Generate Random Number
        
         Random rand = new Random(); //instance of random class
      int upperbound = 101;
        //generate random values from 0-100
      int int_random = rand.nextInt(upperbound); 
      jT_points.setText(Integer.toString(rand.nextInt(int_random)));
      jT_defence.setText(Integer.toString(rand.nextInt(int_random)));
      jT_agility.setText(Integer.toString(rand.nextInt(int_random)));
      jT_base_attack.setText(Integer.toString(rand.nextInt(int_random)));
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB_warriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_warriorActionPerformed
        
// Select a warrior
        if(jB_warrior.isSelected()){
           // Load Warrior image
            jL_Character.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warrior.jpeg")));
            
            String desc="Out to overcoming challenge and adversity";
            jTf_CharacterDesc.setText(desc);
            //Generate Random Number
        GenegateRandom();
         
          
      
            
        }
    }//GEN-LAST:event_jB_warriorActionPerformed

    private void jB_wizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_wizardActionPerformed
         // Select a wizard
        if(jB_wizard.isSelected()){
           // Load Wizard image
            jL_Character.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wizard.jpeg")));
            String desc="one skilled in magic : sorcerer";
            jTf_CharacterDesc.setText(desc);
            //Generate Random Number
      GenegateRandom();
            
        }
    }//GEN-LAST:event_jB_wizardActionPerformed

    private void jB_clericActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_clericActionPerformed
        // Select a cleric
        if(jB_cleric.isSelected()){
           // Load cleric image
            jL_Character.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cleric.jpg")));
            String desc=" capable when fighting Wars";
            jTf_CharacterDesc.setText(desc);
            //Generate Random Number
        
         GenegateRandom();
        }
    }//GEN-LAST:event_jB_clericActionPerformed

    private void jB_hammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_hammerActionPerformed
        // Select a hammer
        if(jB_hammer.isSelected()){        }

           // Load hammer image
             jL_Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hammer.jpeg")));
             String desc=" used by foot-soldiers, especially in the defense of fortified walls ";
            jTf_WeaponDesc.setText(desc);
            //Generate Random Number
        
         Random rand = new Random(); //instance of random class
      int upperbound = 101;
        //generate random values from 0-100
      int int_random = rand.nextInt(upperbound); 
      jT_attack_mod.setText(Integer.toString(rand.nextInt(int_random)));
      jT_weight.setText(Integer.toString(rand.nextInt(int_random)));
    }//GEN-LAST:event_jB_hammerActionPerformed

    private void jB_daggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_daggerActionPerformed
         // Select a dagger
        if(jB_dagger.isSelected()){
           // Load dagger image
             jL_Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dagger.jpeg")));
             String desc=" Small and not heavy to use amd crary";
            jTf_WeaponDesc.setText(desc);
            //Generate Random Number
        
         Random rand = new Random(); //instance of random class
      int upperbound = 101;
        //generate random values from 0-100
      int int_random = rand.nextInt(upperbound); 
      jT_attack_mod.setText(Integer.toString(rand.nextInt(int_random)));
      jT_weight.setText(Integer.toString(rand.nextInt(int_random)));
        }
       
    }//GEN-LAST:event_jB_daggerActionPerformed

    private void jB_swordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_swordActionPerformed
        // Select a sword
        if(jB_sword.isSelected()){
           // Load sword image
             jL_Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sword.jpeg")));
             String desc=" Not very heavy and inflicts alot of damage";
            jTf_WeaponDesc.setText(desc);
            //Generate Random Number
        
         Random rand = new Random(); //instance of random class
      int upperbound = 101;
        //generate random values from 0-100
      int int_random = rand.nextInt(upperbound); 
      jT_attack_mod.setText(Integer.toString(rand.nextInt(int_random)));
      jT_weight.setText(Integer.toString(rand.nextInt(int_random)));
        }
    }//GEN-LAST:event_jB_swordActionPerformed

    private void btn_start_battleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start_battleActionPerformed
       //Direct To Battle Summary Screen
       BattleSummaryScreen bsc=new BattleSummaryScreen();
       this.setVisible(false);
       bsc.setVisible(true);
       
       
       
    }//GEN-LAST:event_btn_start_battleActionPerformed

    private void jT_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_pointsActionPerformed
        
      
        
    }//GEN-LAST:event_jT_pointsActionPerformed

    private void jT_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterCreationScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start_battle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jB_cleric;
    private javax.swing.JRadioButton jB_dagger;
    private javax.swing.JRadioButton jB_hammer;
    private javax.swing.JRadioButton jB_sword;
    private javax.swing.JRadioButton jB_warrior;
    private javax.swing.JRadioButton jB_wizard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_Character;
    private javax.swing.JLabel jL_Weapon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jT_agility;
    private javax.swing.JTextField jT_attack_mod;
    private javax.swing.JTextField jT_base_attack;
    private javax.swing.JTextField jT_defence;
    private javax.swing.JTextField jT_name;
    private javax.swing.JTextField jT_points;
    private javax.swing.JTextField jT_weight;
    private javax.swing.JTextField jTf_CharacterDesc;
    private javax.swing.JTextField jTf_WeaponDesc;
    // End of variables declaration//GEN-END:variables
}
